source("loadData.r")
par(mfrow = c(2, 2), mar = c(4, 4, 2,1 ), oma = c(0, 0, 2, 0))
plot(x=data$dateTime,y=data$Global_active_power,type="l",ylab = "Global Active Power",xlab="")
plot(x=data$dateTime,y=data$Voltage,type="l",ylab = "Voltage",xlab="datetime")
plot(x=data$dateTime,y=data$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="",lwd=2.5)
lines(data$dateTime,data$Sub_metering_2,col="red", lwd=2.5,type="l")
lines(data$dateTime,data$Sub_metering_3,col="blue",lwd=2.5,type="l")
legend("topright",  col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),lty=c(1,1,1))
plot(x=data$dateTime,y=data$Global_reactive_power,type="l",ylab = "Global_reactive_power",xlab="datetime")
